pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE_NAME = 'paytm-clone-app'
        DOCKERHUB_USERNAME = 'muthukannanmuruga'
        DOCKERHUB_CREDENTIAL_ID = 'docker_credential'
        AWS_REGION = 'ap-south-1'
        AWS_CREDENTIAL_ID = 'aws-credentials'
        GITHUB_PAT_CREDENTIAL_ID = 'github_pat'
    }
    
    stages {
        stage('Create Directories') {
            steps {
                script {
                    if (!fileExists('app_code')) {
                        sh 'mkdir app_code'
                    }
                    
                    if (!fileExists('helm_code')) {
                        sh 'mkdir helm_code'
                    }
                }
            }
        }

        stage('Clone App Code Repo') {
            steps {
                dir('app_code') {
                    git url: 'https://github.com/muthukannanmuruga/paytmclone.git', branch: 'main'
                }
            }
        }

        stage('Clone Helm Chart Repo') {
            steps {
                dir('helm_code') {
                    git url: 'https://github.com/muthukannanmuruga/HelmchartforPaytmclone.git', branch: 'main'
                }
            }
        }

        stage('Add dependencies') {
            steps {
                dir('app_code/backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('app_code/backend') {
                        sh "docker build -t ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} ."
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIAL_ID, usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        sh """
                        echo "${DOCKERHUB_PASSWORD}" | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
                        docker tag ${DOCKER_IMAGE_NAME}:${BUILD_NUMBER} ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
                        docker push ${DOCKERHUB_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
                        """
                    }
                }
            }
        }

        stage('Update Helm Chart Image Tag') {
            steps {
                script {
                    dir('helm_code') {
                        sh "sed -i 's/tag: .*/tag: ${BUILD_NUMBER}/' values.yaml"
                        
                        sh 'git status'

                        sh 'git add values.yaml'
                        
                        withCredentials([string(credentialsId: GITHUB_PAT_CREDENTIAL_ID, variable: 'GITHUB_PAT')]) {
                            sh 'git config user.email "muthukannan.muruga@gmail.com"'
                            sh 'git config user.name "muthukannanmuruga"'
                            sh 'git commit -m "Update image tag in values.yaml with build number ${BUILD_NUMBER}"'
                            sh 'git push https://$GITHUB_PAT@github.com/muthukannanmuruga/HelmchartforPaytmclone.git main'
                        }
                    }
                }
            }
        }
    }
}
