pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = 'paytm-clone-app'
        DOCKERHUB_USERNAME = 'muthukannanmuruga'
        DOCKERHUB_CREDENTIAL_ID = 'docker_credential'
    }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/muthukannanmuruga/paytmclone.git'
            }
        }

        stage('Add dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    dir('backend') {
                        sh "docker build -t $DOCKER_IMAGE_NAME ."
                    }
                }
            }
        }
        
        stage('Push to DockerHub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIAL_ID, usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        // Log in to DockerHub and push Docker image
                        sh """
                        echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
                        docker tag $DOCKER_IMAGE_NAME $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
                        docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME
                        """
                    }
                }
            }
        }

        
        // Add more stages as needed
    }
    // Add post-build actions if necessary
}
